#!/bin/sh -e
#
# ==============================================================================
# PAQUETE: desktop-base
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Sasha Veronica Solano Grosjean <sashasolano@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
	printf "\033[1;31m${1}\033[0m\n"
}

ADVERTENCIA() {
	printf "\033[1;33m${1}\033[0m\n"
}

EXITO() {
	printf "\033[1;32m${1}\033[0m\n"
}

#PLYMOUTHCONF="/etc/plymouth/plymouthd.conf"
#INITRAMFSMOD="/etc/initramfs-tools/modules"
#INITRAMFSPLASH="/etc/initramfs-tools/conf.d/splash"

case ${1} in

    configure|'')

	if [ -e /etc/init.d/plymouth ]; then
		sed -i 's/TEXT="Shutting down system..."/TEXT="Apagando el equipo..."/g' /etc/init.d/plymouth
		sed -i 's/TEXT="Restarting system..."/TEXT="Reiniciando el equipo..."/g' /etc/init.d/plymouth
	fi

	# Segun sea la marca de la tarjeta de video, se deben cargar diferentes modulos 
	# mediante el archivo /etc/initramfs-tools/modules.
	#if [ $( lspci | grep "VGA" | grep -iwc "nvidia" ) -eq 1 ]; then
	#	WARNING "Configurando Plymouth para tarjeta NVIDIA ..."
	#	if [ $( cat ${INITRAMFSMOD} | grep -iwc "^drm$" ) -eq 0 ] \
	#	&& [ $( cat ${INITRAMFSMOD} | grep -iwc "^nouveau modeset=1$" ) -eq 0 ]; then
	#		echo "drm" >> ${INITRAMFSMOD}
	#		echo "nouveau modeset=1" >> ${INITRAMFSMOD}
	#	fi
	#fi

	#if [ $( lspci | grep "VGA" | grep -iwc "intel" ) -eq 1 ]; then
	#	WARNING "Configurando Plymouth para tarjeta INTEL ..."
	#	if [ $( cat ${INITRAMFSMOD} | grep -iwc "^intel_agp$" ) -eq 0 ] \
	#	&& [ $( cat ${INITRAMFSMOD} | grep -iwc "^drm$" ) -eq 0 ] \
	#	&& [ $( cat ${INITRAMFSMOD} | grep -iwc "^i915 modeset=1$" ) -eq 0 ]; then
	#		echo "intel_agp" >> ${INITRAMFSMOD}
	#		echo "drm" >> ${INITRAMFSMOD}
	#		echo "i915 modeset=1" >> ${INITRAMFSMOD}
	#	fi
	#fi

	#if [ $( lspci | grep "VGA" | grep -iwc "ati" ) -eq 1 ]; then 
	#	WARNING "Configurando Plymouth para tarjeta ATI ..."
	#	if [ $( cat ${INITRAMFSMOD} | grep -iwc "^uvesafb mode_option=800x600 mtrr=3 scroll=ywrap$" ) -eq 0 ] \
	#	&& [ $( cat ${INITRAMFSPLASH} | grep -iwc "^FRAMEBUFFER=y$" ) -eq 0 ]; then
	#		echo "uvesafb mode_option=800x600 mtrr=3 scroll=ywrap" >> ${INITRAMFSMOD}
	#		echo "FRAMEBUFFER=y" >> ${INITRAMFSPLASH}
	#	fi
	#fi

	if [ -n "$( which plymouth-set-default-theme )" ] && [ -x "$( which plymouth-set-default-theme )" ]; then
		plymouth-set-default-theme Gnamon || true
	fi

	# Alternatives for the background
	while read background priority; do
        update-alternatives --install \
            /usr/share/images/desktop-base/desktop-background \
            desktop-background \
            /usr/share/images/desktop-base/$background $priority
    done << EOF
01_trompo.jpg 50
02_canaima.jpg 40
03_guacamaya.jpg 30
04_costa.jpg 20
05_laguna.jpg 10
EOF

    # Set up an alternative for the XML version of the background
    # (for GNOME)
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background.xml \
        desktop-background.xml \
        /usr/share/images/desktop-base/canaima.xml 70

    # Alternatives for grub
	update-alternatives --install \
		/usr/share/images/desktop-base/desktop-grub.png \
		desktop-grub \
		/usr/share/images/desktop-base/grub.png 70

    # Reload gdm3 configuration
    if [ -n "$( which gdm3 )" ] && [ -x "$( which gdm3 )" ]; then
        invoke-rc.d gdm3 reload || true
    fi

	# Se actualiza el archivo de inicializacion que se ejecuta al iniciar el equipo
	if [ -n "$( which update-initramfs )" ] && [ -x "$( which update-initramfs )" ]; then
		update-initramfs -u
	fi

	if [ -n "$( which update-burg )" ] && [ -x "$( which update-burg )" ]; then
		sync
		update-burg || true
	fi

	if [ -n "$( which update-grub )" ] && [ -x "$( which update-grub )" ]; then
		sync
		update-grub || true
	fi

    if [ -e /etc/init.d/plymouth ]; then

        sed -i -e's/TEXT=\"Shutting down system...\"/TEXT=\"Hasta Luego , apagando el sistema...\"/g' /etc/init.d/plymouth

    fi

    if [ -e /etc/init.d/plymouth ]; then

        sed -i -e's/TEXT=\"Restarting system...\"/TEXT=\"Reiniciando el sistema...\"/g' /etc/init.d/plymouth

    fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
		ERROR "postinst no reconoce el argumento '"${1}"'" >&2
		exit 1
    ;;

esac

#DEBHELPER#

exit 0
