#!/bin/sh -e
#
# ==============================================================================
# PAQUETE: desktop-base
# ARCHIVO: postrm
# DESCRIPCIÓN: Revierte los cambios hechos por el paquete en los scripts del
#              mantenedor, de forma tal de asegurarse que el sistema quede
#              como estaba antes de su instalación.
# COPYRIGHT:
#  (C) 2010 Sasha Veronica Solano Grosjean <sashasolano@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
	printf "\033[1;31m${1}\033[0m\n"
}

ADVERTENCIA() {
	printf "\033[1;33m${1}\033[0m\n"
}

EXITO() {
	printf "\033[1;32m${1}\033[0m\n"
}

#PLYMOUTHCONF="/etc/plymouth/plymouthd.conf"
#INITRAMFSMOD="/etc/initramfs-tools/modules"
#INITRAMFSPLASH="/etc/initramfs-tools/conf.d/splash"

case ${1} in

    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|deconfigure)

	#if [ -e /etc/init.d/plymouth ]; then
	#	sed -i 's/TEXT="Apagando el equipo... Recuerda: ¡Ahorrar energía es salvar al planeta!"/TEXT="Shutting down system..."/g' /etc/init.d/plymouth
	#	sed -i 's/TEXT="Reiniciando el equipo..."/TEXT="Restarting system..."/g' /etc/init.d/plymouth
	#fi

	# Segun sea la marca de la tarjeta de video, se deben cargar diferentes modulos 
	# mediante el archivo /etc/initramfs-tools/modules.
	#if [ $( lspci | grep "VGA" | grep -iwc "nvidia" ) -eq 1 ]; then
	#	ADVERTENCIA "Removiendo configuración de Canaima Plymouth para tarjeta NVIDIA ..."
	#	sed -i 's/^drm$//g' ${INITRAMFSMOD}
	#	sed -i 's/^nouveau modeset=1$//g' ${INITRAMFSMOD}
	#fi

	#if [ $( lspci | grep "VGA" | grep -iwc "intel" ) -eq 1 ]; then
	#	ADVERTENCIA "Removiendo configuración de Canaima Plymouth para tarjeta INTEL ..."
	#	sed -i 's/^intel_agp$//g' ${INITRAMFSMOD}
	#	sed -i 's/^drm$//g' ${INITRAMFSMOD}
	#	sed -i 's/^i915 modeset=1$//g' ${INITRAMFSMOD}
	#fi

	#if [ $( lspci | grep "VGA" | grep -iwc "ati" ) -eq 1 ]; then 
	#	ADVERTENCIA "Removiendo configuración de Canaima Plymouth para tarjeta ATI ..."
	#	sed -i 's/^uvesafb mode_option=800x600 mtrr=3 scroll=ywrap$//g' ${INITRAMFSMOD}
	#	sed -i 's/^FRAMEBUFFER=y$//g' ${INITRAMFSPLASH}
	#fi

	if [ -n $( which plymouth-set-default-theme ) ] && [ -x $( which plymouth-set-default-theme ) ]; then
		plymouth-set-default-theme text || true
	fi

    # Reload gdm3 configuration
    if [ -n "$( which gdm3 )" ] && [ -x "$( which gdm3 )" ]; then
        invoke-rc.d gdm3 reload || true
    fi

	# Se actualiza el archivo de inicializacion que se ejecuta al iniciar el equipo
	if [ -n "$( which update-initramfs )" ] && [ -x "$( which update-initramfs )" ]; then
		update-initramfs -u
	fi

	if [ -n "$( which update-burg )" ] && [ -x "$( which update-burg )" ]; then
		sync
		update-burg || true
	fi

	if [ -n "$( which update-grub )" ] && [ -x "$( which update-grub )" ]; then
		sync
		update-grub || true
	fi

    ;;

    *)
		ERROR "postinst no reconoce el argumento '"${1}"'" >&2
		exit 1
    ;;

esac

#DEBHELPER#

exit 0
