#!/bin/bash -e

#DEBHELPER#

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
  dpkg-maintscript-helper rm_conffile /etc/kde3/kdeglobals 6.0.1 -- "$@"
fi

if [ "${1}" = "configure" ] && [ "$2" != "" ] ; then

    if dpkg --compare-versions ${2} lt 0.3.11 && dpkg --compare-versions ${2} gt 0.3.5; then
        if test -x /var/lib/dpkg/info/libgnome2-common.postinst; then
            /var/lib/dpkg/info/libgnome2-common.postinst configure
        fi
    fi
fi

if [ "$1" = "configure" -o "$1" = "abort-upgrade" ]; then
    # Alternatives for the background
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background \
        desktop-background \
        /usr/share/images/desktop-base/canaima-fondo-musgo-2.png 60

    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background \
        desktop-background \
        /usr/share/images/desktop-base/canaima-selva-vectorial-bohemio.png 45

    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background \
        desktop-background \
        /usr/share/images/desktop-base/canaima-cordillera.png 30

    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background \
        desktop-background \
        /usr/share/images/desktop-base/canaima-vectores-pasteles-1.png 20

    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background \
        desktop-background \
        /usr/share/images/desktop-base/canaima-vectores-pasteles-2.png 15

    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background \
        desktop-background \
        /usr/share/images/desktop-base/canaima-vectores-pasteles-3.png 10

    # Alternatives for the splash
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-splash \
        desktop-splash \
        /usr/share/images/desktop-base/canaima-gnome-splash.png 90

    # Alternatives for grub
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-grub.png \
        desktop-grub \
        /usr/share/images/desktop-base/canaima-grub.png 90

    # GRUB background
    if which update-grub2 > /dev/null ; then
        sync
        update-grub2 || true
    fi

    # Splashy
    if [ -x /sbin/splashy_config ] && [ -w /etc/splashy/config.xml ]; then
        splashy_config --set-theme spacefun
    fi

    # Plymouth
    if [ -x /usr/sbin/plymouth-set-default-theme ];
    then
      plymouth-set-default-theme canaima-plymouth ||true
    fi

    if [ -x /usr/sbin/update-initramfs ]; then
        update-initramfs -u
    fi
fi
