#!/bin/sh -e
#
# ==============================================================================
# PAQUETE: desktop-base
# ARCHIVO: preinst
# DESCRIPCIÓN: Configura el sistema antes de la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Sasha Veronica Solano Grosjean <sashasolano@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
	printf "\033[1;31m${1}\033[0m\n"
}

ADVERTENCIA() {
	printf "\033[1;33m${1}\033[0m\n"
}

EXITO() {
	printf "\033[1;32m${1}\033[0m\n"
}

case ${1} in

	install)
	;;

	upgrade)

		if dpkg --compare-versions ${2} lt 0.3.11 && dpkg --compare-versions ${2} gt 0.3.5; then
			update-alternatives --remove gnome-splash \
				/usr/share/images/desktop-base/Splash-Debian.png
			update-alternatives --remove gnome-splash \
				/usr/share/images/desktop-base/Splash-EvolvingTux.png
			update-alternatives --remove gnome-splash \
				/usr/share/images/desktop-base/Splash-Debian_red.png
			dpkg-divert --package desktop-base --rename \
				--divert /usr/share/pixmaps/splash/gnome-splash.png.orig \
				--remove /usr/share/pixmaps/splash/gnome-splash.png
		fi

		if dpkg --compare-versions "$2" lt-nl 7; then
			update-alternatives --remove desktop-grub /usr/share/images/desktop-base/moreblue-orbit-grub.png
		fi
	
		if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
			dpkg-maintscript-helper rm_conffile /etc/kde3/kdeglobals 6.0.1 -- "$@"
		fi

	;;

	abort-upgrade)
	;;

	*)
		ERROR "preinst no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
