#!/bin/sh -e

#DEBHELPER#

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then

    # remove background alternatives
    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-fondo-musgo-2.png

    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-selva-vectorial-bohemio.png

    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-cordillera.png

    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-vectores-pasteles-1.png

    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-vectores-pasteles-2.png

    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-vectores-pasteles-3.png

    # remove splash alternatives
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-splash \
        desktop-splash \
        /usr/share/images/desktop-base/canaima-gnome-splash.png

    # remove grub alternatives
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-grub.png \
        desktop-grub \
        /usr/share/images/desktop-base/canaima-grub.png
fi
