#!/bin/sh -e
#
# ==============================================================================
# PAQUETE: desktop-base
# ARCHIVO: prerm
# DESCRIPCIÓN: Prepara el sistema para que el paquete sea removido.
# COPYRIGHT:
#  (C) 2010 Sasha Veronica Solano Grosjean <sashasolano@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
	printf "\033[1;31m${1}\033[0m\n"
}

ADVERTENCIA() {
	printf "\033[1;33m${1}\033[0m\n"
}

EXITO() {
	printf "\033[1;32m${1}\033[0m\n"
}

case ${1} in

	remove|upgrade|deconfigure)

	    # remove background alternatives
		for background in \
			minimal.png \
			brillante.png \
			cascada.png \
			descanso.png \
			islazapara.png \
			llanero.png \
			selva.png \
			; do
			update-alternatives --remove desktop-background /usr/share/images/desktop-base/$background
		done

		update-alternatives --remove desktop-background.xml /usr/share/images/desktop-base/canaima.xml
		update-alternatives --remove desktop-grub /usr/share/images/desktop-base/grub.png
		
	;;

	failed-upgrade)
	;;

	*)
		ERROR "prerm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
