#!/bin/sh -e

#DEBHELPER#

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then

    # remove background alternatives
    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-fondo-musgo.svg

    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-fondo-jaspe.svg

    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-fondo-playa.svg

    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-fondo-python.svg

    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-fondo-abstracto.jpg

    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-fondo-pastel.png

    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-fondo-amanecer.png

    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-fondo-atardecer.png

    update-alternatives --remove \
        desktop-background \
        /usr/share/images/desktop-base/canaima-fondo-viejo.png

    # remove splash alternatives
    update-alternatives --remove \
        desktop-splash \
        /usr/share/images/desktop-base/canaima-gnome-splash.svg

    update-alternatives --remove \
        desktop-splash \
        /usr/share/images/desktop-base/canaima-gnome-splash-viejo.png

    # remove grub alternatives
    update-alternatives --remove \
        desktop-grub \
        /usr/share/images/desktop-base/canaima-grub.png

    update-alternatives --remove \
        desktop-grub \
        /usr/share/images/desktop-base/canaima-grub-viejo.png
fi
